[package]
name = "kcl-lang"
version = "0.8.0-alpha.2"
edition = "2021"
readme = "README.md"
documentation = "kcl-lang.io"
description = "KCL Rust SDK"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.8"
prost-types = "0.11.8"
serde_json = "1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
libloading = "0.7.3"
tempfile = "3.5.0"
