[package]
name = "kcl-wasm-lib"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
wasmtime = "21.0.1"
wasmtime-wasi = "21.0.1"
