[package]
name = "kcl-lib-cpp"
publish = false
edition = "2024"
version = "0.12.2"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0"
cxx = "1.0"
kcl-api = { git = "https://github.com/kcl-lang/kcl", version = "0.12.2" }

[build-dependencies]
cxx-build = "1.0"
