[package]
name = "kcl-lib-cpp"
publish = false
edition = "2021"
version = "0.10.0-alpha.1"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0"
cxx = "1.0"
kclvm-api = { git = "https://github.com/kcl-lang/kcl", version = "0.10.0-alpha.1" }

[build-dependencies]
cxx-build = "1.0"
