[package]
name = "kcl-lib-dotnet"
publish = false
version = "0.12.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]
doc = false

[dependencies]
kcl-api = { git = "https://github.com/kcl-lang/kcl", version = "0.12.2" }
